from config.database import SessionLocal
from modules.database.models import MailForgeFollowUp, MailForgeDraft
from datetime import datetime, timedelta
from utils.logging_utils import get_logger

logger = get_logger(__name__)

class MailForgeFollowUpService:
    def create_followups_for_draft(self, draft_id: str, followups_data: list[dict]) -> bool:
        """
        Takes list of followup dictionaries generated by generator and saves them to the DB.
        """
        db = SessionLocal()
        try:
            draft = db.query(MailForgeDraft).filter(MailForgeDraft.id == draft_id).first()
            if not draft:
                logger.error(f"Cannot find parent draft {draft_id}")
                return False

            # Delete any existing followups for this draft first
            existing = db.query(MailForgeFollowUp).filter(
                MailForgeFollowUp.parent_draft_id == draft_id
            ).all()
            for e in existing:
                db.delete(e)
            db.flush()

            for f_data in followups_data:
                fup = MailForgeFollowUp(
                    mailforge_campaign_id=draft.mailforge_campaign_id,
                    lead_id=draft.lead_id,
                    parent_draft_id=draft.id,
                    followup_number=f_data.get("followup_number", 1),
                    subject=f_data.get("subject", f"Re: {draft.subject}"),
                    body=f_data.get("body", ""),
                    scheduled_after_days=f_data.get("scheduled_after_days", 3),
                    status="pending"
                )
                db.add(fup)
            
            db.commit()
            return True
        except Exception as e:
            db.rollback()
            logger.error(f"Failed to save follow-ups for draft {draft_id}: {e}")
            return False
        finally:
            db.close()

    def get_campaign_followups(self, campaign_id: str) -> list:
        """
        Get all followups for a specific campaign.
        """
        db = SessionLocal()
        try:
            return db.query(MailForgeFollowUp).filter(
                MailForgeFollowUp.mailforge_campaign_id == campaign_id
            ).all()
        finally:
            db.close()
